### ISSUE TITLE
got java.lang.IllegalArgumentException when generating parse.sdeps.combined file

### ISSUE THREAD

**Issue by zhouksh** [strubell/preprocess-conll05#3]
hi, right now I am following this repository. Everything goes fine except that when generating parse.sdeps.combined file, I ran into a java exception throw by the stanford package. The parse.sdeps.combined file is generated, though.

-------------------------------
Exception in thread "main" java.lang.IllegalArgumentException: No head rule defined for NP* using class edu.stanford.nlp.trees.SemanticHeadFinder in (NP*
  .
  (NNP Oc)
  CD
  19
  *
  NN
  review
  *)

	at edu.stanford.nlp.trees.AbstractCollinsHeadFinder.determineNonTrivialHead(AbstractCollinsHeadFinder.java:246)
	at edu.stanford.nlp.trees.SemanticHeadFinder.determineNonTrivialHead(SemanticHeadFinder.java:452)
	at edu.stanford.nlp.trees.AbstractCollinsHeadFinder.determineHead(AbstractCollinsHeadFinder.java:193)
	at edu.stanford.nlp.trees.TreeGraphNode.percolateHeads(TreeGraphNode.java:319)
	at edu.stanford.nlp.trees.TreeGraphNode.percolateHeads(TreeGraphNode.java:317)
	at edu.stanford.nlp.trees.TreeGraphNode.percolateHeads(TreeGraphNode.java:317)
	at edu.stanford.nlp.trees.TreeGraphNode.percolateHeads(TreeGraphNode.java:317)
	at edu.stanford.nlp.trees.TreeGraphNode.percolateHeads(TreeGraphNode.java:317)
	at edu.stanford.nlp.trees.GrammaticalStructure.<init>(GrammaticalStructure.java:184)
	at edu.stanford.nlp.trees.EnglishGrammaticalStructure.<init>(EnglishGrammaticalStructure.java:86)
	at edu.stanford.nlp.parser.lexparser.EnglishTreebankParserParams.getGrammaticalStructure(EnglishTreebankParserParams.java:2355)
	at edu.stanford.nlp.trees.GrammaticalStructureConversionUtils$TreeBankGrammaticalStructureWrapper$GsIterator.primeGs(GrammaticalStructureConversionUtils.java:410)
	at edu.stanford.nlp.trees.GrammaticalStructureConversionUtils$TreeBankGrammaticalStructureWrapper$GsIterator.<init>(GrammaticalStructureConversionUtils.java:397)
	at edu.stanford.nlp.trees.GrammaticalStructureConversionUtils$TreeBankGrammaticalStructureWrapper.iterator(GrammaticalStructureConversionUtils.java:373)
	at edu.stanford.nlp.trees.GrammaticalStructureConversionUtils.convertTrees(GrammaticalStructureConversionUtils.java:739)
	at edu.stanford.nlp.trees.EnglishGrammaticalStructure.main(EnglishGrammaticalStructure.java:2219)
POS tagging: /Users/work/Workspace/git/preprocess-conll05/conll05st-release/train-set.gz.parse.sdeps
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

-------------------------------
Above is the error message I got. I am wondering if it's OK to ignore this message since the parse.sdeps.combined file is generated. If not, how can I solve it. Thanks for your help in advance !

**Comment by zhouksh** [comment]
It seems like under MacOS environment, one may run into some issue regarding difference between Mac sed and GNU sed. Switch to Linux environment solve the problem.
